server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.yandex.ru
    port: 587
    username: example@yandex.ru
    password: pass
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.yandex.ru

#jira:
#  base-url: https://your-company.atlassian.net
#  username: api-user@company.com
#  api-token: your-api-token

app:
  queues:
    application: applications.queue
    interview: interview.queue